# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eac1cbef959865ec009334055e8facaee02946b4261cba16803a6549f16f5b98d4abe451746735ac24fba52d15e6c7bfe4cde29486eb5be9de2ad6ed5ed5656

test:
  secret_key_base: 2382b31a6881d60ef0bf72af7a08d7a5b005d3fad1b7915e4622df0ed26d2fb0d6fb254d93d1f77db6467f29aeb155de30be3ba432c0017d42a04258031ec6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
